  wget http://www.cacpd.org/climate_normals/NA_Reference_files_netCDF.7z
  wget http://www.cacpd.org/climate_normals/NA_NORM_6190_Bioclim_netCDF.7z
  wget http://www.cacpd.org/climate_normals/NA_NORM_6190_Monthly_netCDF.7z
  wget http://www.cacpd.org/climate_normals/NA_NORM_8110_Bioclim_netCDF.7z
  wget http://www.cacpd.org/climate_normals/NA_NORM_8110_Monthly_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp45_2020s_Bioclim_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp45_2020s_Monthly_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp45_2050s_Bioclim_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp45_2050s_Monthly_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp45_2080s_Bioclim_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp45_2080s_Monthly_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp85_2020s_Bioclim_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp85_2020s_Monthly_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp85_2050s_Bioclim_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp85_2050s_Monthly_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp85_2080s_Bioclim_netCDF.7z
  wget http://www.cacpd.org/ensemble_AOGCMs/NA_ENSEMBLE_rcp85_2080s_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CCSM4_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CNRM-CM5_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/CanESM2_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/GFDL-CM3_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/HadGEM2-ES_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/INM-CM4_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/IPSL-CM5A-MR_rcp85_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp45_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp45_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp45_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp45_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp45_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp45_2085_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp85_2025_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp85_2025_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp85_2055_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp85_2055_Monthly_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp85_2085_Bioclim_netCDF.7z
  wget http://www.cacpd.org/selected_AOGCMs/MPI-ESM-LR_rcp85_2085_Monthly_netCDF.7z
